import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

type Locale = "en" | "it";

interface Translations {
  [key: string]: { en: string; it: string };
}

const translations: Translations = {
  // Nav
  "nav.home": { en: "Home", it: "Home" },
  "nav.myCovers": { en: "My Covers", it: "Le Mie Coperture" },
  "nav.myClaims": { en: "My Claims", it: "I Miei Incidenti" },
  "nav.dashboard": { en: "Dashboard", it: "Dashboard" },
  "nav.customers": { en: "Customers", it: "Clienti" },
  "nav.covers": { en: "Covers", it: "Coperture" },
  "nav.claims": { en: "Claims", it: "Incidenti" },
  "nav.team": { en: "Team", it: "Team" },
  "nav.insights": { en: "Insights", it: "Insights" },
  "nav.aiQuery": { en: "Ask the data", it: "Chiedi ai dati" },
  "nav.assistant": { en: "Assistant", it: "Assistente" },
  "nav.knowledge": { en: "Knowledge base", it: "Knowledge base" },
  "nav.shops": { en: "Shops", it: "Boutique" },
  "nav.settings": { en: "Settings", it: "Impostazioni" },

  // Insights — Gross-margin tab + Feedback themes tile (added with brand wow features).
  // The data only supports gross margin (revenue - cogs) — we don't have the
  // brand's full cost stack, so don't claim "net profit".
  "insights.tab.profit": { en: "Margin", it: "Margine" },
  "insights.profit.disclaimer": {
    en: "Gross margin only — based on COGS. Doesn't include operating, marketing, or other costs.",
    it: "Solo margine lordo — basato sul COGS. Non include costi operativi, marketing o altri costi.",
  },
  "insights.profit.kpi.revenue": { en: "Revenue (live)", it: "Ricavi (attivi)" },
  "insights.profit.kpi.cogs": { en: "COGS", it: "COGS" },
  "insights.profit.kpi.grossMargin": { en: "Gross margin", it: "Margine lordo" },
  "insights.profit.kpi.grossMarginPct": { en: "Gross margin %", it: "Margine lordo %" },
  "insights.profit.chart.byCategory": { en: "Revenue vs gross margin by category", it: "Ricavi vs margine lordo per categoria" },
  "insights.profit.chart.topShops": { en: "Top shops by gross margin", it: "Boutique per margine lordo" },
  "insights.profit.chart.byMonth": { en: "Monthly revenue & gross margin", it: "Ricavi e margine lordo mensili" },
  "insights.profit.legend.revenue": { en: "Revenue", it: "Ricavi" },
  "insights.profit.legend.grossMargin": { en: "Gross margin", it: "Margine lordo" },
  "insights.themes.title": { en: "Customer feedback themes", it: "Temi nel feedback clienti" },
  "insights.themes.commentsLast30": { en: "comments in the last 30 days", it: "commenti negli ultimi 30 giorni" },
  "insights.themes.loading": { en: "Analysing feedback…", it: "Analisi feedback…" },
  "insights.themes.updatedOn": { en: "updated", it: "aggiornato il" },
  "insights.themes.refresh": { en: "Refresh", it: "Aggiorna" },
  "insights.themes.refreshing": { en: "Refreshing…", it: "Aggiornamento…" },
  "insights.themes.empty": { en: "No customer comments yet in this window.", it: "Nessun commento dei clienti in questo periodo." },

  // BrandCustomers — segment chips
  "brandCustomers.segment.all": { en: "All", it: "Tutti" },
  "brandCustomers.segment.vip": { en: "VIP", it: "VIP" },
  "brandCustomers.segment.lapsed": { en: "Lapsed", it: "Inattivi" },
  "brandCustomers.segment.incomplete": { en: "Profile incomplete", it: "Profilo incompleto" },
  "brandCustomers.segment.highNpsIdle": { en: "Happy but idle", it: "Soddisfatti ma fermi" },
  // BrandCustomers — sort dropdown
  "brandCustomers.sort.newest": { en: "Newest first", it: "Più recenti" },
  "brandCustomers.sort.oldest": { en: "Oldest first", it: "Più vecchi" },
  "brandCustomers.sort.name": { en: "Name A–Z", it: "Nome A–Z" },
  "brandCustomers.sort.ltv": { en: "Highest LTV", it: "LTV più alto" },
  // BrandCustomers — column headers + row badges
  "brandCustomers.column.ltv": { en: "LTV", it: "LTV" },
  "brandCustomers.badge.vip": { en: "VIP", it: "VIP" },
  "brandCustomers.badge.lapsed": { en: "Lapsed", it: "Inattivo" },
  "brandCustomers.badge.incomplete": { en: "Incomplete", it: "Incompleto" },
  "brandCustomers.badge.happyIdle": { en: "Happy/idle", it: "Sodd./fermo" },

  // Brand nav — renewals
  "nav.renewals": { en: "Renewals", it: "Rinnovi" },

  // BrandRenewals page
  "brandRenewals.title": { en: "Renewals", it: "Rinnovi" },
  "brandRenewals.subtitle": {
    en: "Covers expiring in the next 30 days — sorted by urgency so the clienteling team can act before they lapse.",
    it: "Coperture in scadenza nei prossimi 30 giorni — ordinate per urgenza così il team clienteling può intervenire prima della scadenza.",
  },
  "brandRenewals.kpi.totalAtRisk": { en: "Total at risk (30d)", it: "Totale a rischio (30 g)" },
  "brandRenewals.kpi.sevenDays": { en: "7 days", it: "7 giorni" },
  "brandRenewals.kpi.twoWeeks": { en: "8–14 days", it: "8–14 giorni" },
  "brandRenewals.kpi.month": { en: "15–30 days", it: "15–30 giorni" },
  "brandRenewals.bucket.wk": { en: "Expiring in 7 days", it: "In scadenza tra 7 giorni" },
  "brandRenewals.bucket.2w": { en: "Expiring in 8–14 days", it: "In scadenza tra 8–14 giorni" },
  "brandRenewals.bucket.mo": { en: "Expiring in 15–30 days", it: "In scadenza tra 15–30 giorni" },
  "brandRenewals.atRisk": { en: "at risk", it: "a rischio" },
  "brandRenewals.empty": {
    en: "No covers are due to expire in the next 30 days. 🎉",
    it: "Nessuna copertura in scadenza nei prossimi 30 giorni. 🎉",
  },

  // BrandClaims — triage view + flags
  "brandClaims.view.table": { en: "Table", it: "Tabella" },
  "brandClaims.view.triage": { en: "Triage", it: "Triage" },
  "brandClaims.view.flagged": { en: "Flagged", it: "Segnalati" },
  "brandClaims.view.flaggedTitle": {
    en: "Show only claims with fraud-suspicion flags",
    it: "Mostra solo richieste con segnalazioni anti-frode",
  },
  "brandClaims.triage.empty": { en: "No claims to triage.", it: "Nessuna richiesta da gestire." },
  "brandClaims.flag.freshCover": { en: "Fresh cover", it: "Copertura recente" },
  "brandClaims.flag.freshCoverTip": {
    en: "Claim opened within 30 days of cover start — possible last-minute coverage purchase.",
    it: "Richiesta aperta entro 30 giorni dall'inizio della copertura — possibile acquisto all'ultimo minuto.",
  },
  "brandClaims.flag.frequentClaimer": { en: "Frequent claimer", it: "Cliente ricorrente" },
  "brandClaims.flag.frequentClaimerTip": {
    en: "This customer has 3+ claims in the last 12 months.",
    it: "Questo cliente ha 3+ richieste negli ultimi 12 mesi.",
  },
  "brandClaims.flag.repeatCity": { en: "Repeat city", it: "Città ripetuta" },
  "brandClaims.flag.repeatCityTip": {
    en: "Same customer has 2+ claims in this same incident city.",
    it: "Lo stesso cliente ha 2+ richieste nella stessa città dell'incidente.",
  },
  "nav.menu": { en: "Menu", it: "Menu" },
  "nav.management": { en: "Management", it: "Gestione" },

  // Help
  "help.title": { en: "Need Help?", it: "Hai bisogno di aiuto?" },
  "help.desc": { en: "Contact our support team anytime.", it: "Contatta il nostro team di supporto." },
  "help.contact": { en: "Contact Support", it: "Contatta il Supporto" },
  "help.faq": { en: "Check our FAQ", it: "Consulta le FAQ" },

  // Profile
  "profile.myProfile": { en: "My Profile", it: "Il Mio Profilo" },
  "profile.logout": { en: "Logout", it: "Esci" },

  // Covers page
  "covers.title": { en: "My Covers", it: "Le Mie Coperture" },
  "covers.subtitle": { en: "Track and manage protection for your luxury pieces.", it: "Monitora e gestisci la protezione dei tuoi pezzi di lusso." },
  "covers.openClaim": { en: "Open Claim", it: "Apri Incidente" },
  "covers.transfer": { en: "Transfer", it: "Trasferisci" },
  "covers.startDate": { en: "Start Date", it: "Data Inizio" },
  "covers.expiration": { en: "Expiration", it: "Scadenza" },
  "covers.start": { en: "Start", it: "Inizio" },

  // Dashboard
  "dashboard.completeProfile": { en: "Complete your profile", it: "Completa il tuo profilo" },
  "dashboard.completeProfileDesc": { en: "Complete your profile to unlock all features.", it: "Completa il tuo profilo per sbloccare tutte le funzionalità." },
  "dashboard.completeProfileBtn": { en: "Complete Profile", it: "Completa Profilo" },
  "dashboard.heroTitle": { en: "Prestige Protection", it: "Protezione di Prestigio" },
  "dashboard.viewCovers": { en: "View My Covers", it: "Vedi le Mie Coperture" },
  "dashboard.activeCovers": { en: "Active Covers", it: "Coperture Attive" },
  "dashboard.openClaims": { en: "Open Claims", it: "Incidenti Aperti" },
  "dashboard.totalProtected": { en: "Total Protected Value", it: "Valore Totale Protetto" },
  "dashboard.howItWorks": { en: "How It Works", it: "Come Funziona" },
  "dashboard.step1Title": { en: "Coverage at Checkout", it: "Copertura al Checkout" },
  "dashboard.step1Desc": { en: "Complimentary coverage included with your luxury purchase.", it: "Copertura inclusa con il tuo acquisto di lusso." },
  "dashboard.step2Title": { en: "Simple Activation", it: "Attivazione Semplice" },
  "dashboard.step2Desc": { en: "Activate your coverage effortlessly in just a few clicks.", it: "Attiva la tua copertura in pochi click." },
  "dashboard.step3Title": { en: "Effortless Claims", it: "Incidenti Semplici" },
  "dashboard.step3Desc": { en: "Submit claims quickly through our intuitive platform.", it: "Invia incidenti rapidamente tramite la nostra piattaforma intuitiva." },

  // Auth
  "auth.login": { en: "Log In", it: "Accedi" },
  "auth.signup": { en: "Sign Up", it: "Registrati" },
  "auth.email": { en: "Email", it: "Email" },
  "auth.password": { en: "Password", it: "Password" },
  "auth.forgotPassword": { en: "Forgot Password?", it: "Password dimenticata?" },
  "auth.noAccount": { en: "Don't have an account?", it: "Non hai un account?" },
  "auth.hasAccount": { en: "Already have an account?", it: "Hai già un account?" },
  "auth.welcomeBack": { en: "Welcome back", it: "Bentornato" },
  "auth.createAccount": { en: "Create your account", it: "Crea il tuo account" },
  "auth.fullName": { en: "Full Name", it: "Nome Completo" },

  // FAQ
  "faq.title": { en: "Frequently Asked Questions", it: "Domande Frequenti" },
  "faq.search": { en: "Search questions...", it: "Cerca domande..." },
  "faq.subtitle": { en: "Find answers to the most common questions about our service.", it: "Trova le risposte alle domande più frequenti sul nostro servizio." },
  "faq.empty": { en: "No questions match your search.", it: "Nessuna domanda corrisponde alla tua ricerca." },
  "faq.backToLogin": { en: "Back to login", it: "Torna al login" },

  // Dashboard — Prestige Service
  "dashboard.prestigeService": { en: "Prestige Service", it: "Servizio Prestige" },
  "dashboard.seeAllProducts": { en: "See All Products", it: "Vedi tutti i prodotti" },
  "dashboard.heroDesc": { en: "Inspired by its passion for customer excellence, {brand} is pleased to introduce an exclusive cover service.", it: "Ispirato dalla passione per l'esperienza del cliente, {brand} è lieto di presentare un servizio di copertura esclusivo." },
  "dashboard.prestigeServiceDesc": { en: "The {brand} Prestige Service is a complimentary 2-year program designed to protect your {brand} jewelry against theft and accidental damage.", it: "Il Servizio Prestige di {brand} è un programma gratuito di 2 anni progettato per proteggere i tuoi gioielli {brand} da furto e danni accidentali." },
  "dashboard.theft": { en: "Theft", it: "Furto" },
  "dashboard.theftDesc": { en: "In the event of theft, {brand} team will carefully review your case. If all prerequisites are met, {brand} may, at its sole discretion, offer a replacement jewelry of equal value via a digital voucher.", it: "In caso di furto, il team {brand} esaminerà attentamente il tuo caso. Se tutti i prerequisiti sono soddisfatti, {brand} può, a sua esclusiva discrezione, offrire un gioiello sostitutivo di pari valore tramite un voucher digitale." },
  "dashboard.accidentalDamage": { en: "Accidental damage", it: "Danni Accidentali" },
  "dashboard.damageDesc": { en: "In the event of irreparable accidental damage, {brand} will carefully review your case. If all prerequisites are met, {brand} may, at its sole discretion, offer a replacement jewelry of equal value via a digital voucher.", it: "In caso di danni accidentali irreparabili, {brand} esaminerà attentamente il tuo caso. Se tutti i prerequisiti sono soddisfatti, {brand} può, a sua esclusiva discrezione, offrire un gioiello sostitutivo di pari valore tramite un voucher digitale." },
  "dashboard.faq": { en: "FAQ", it: "FAQ" },
  "dashboard.viewMore": { en: "View More", it: "Vedi Altro" },
  "dashboard.feedbackTitle": { en: "Please rate {brand} Prestige Service", it: "Valuta il Servizio Prestige di {brand}" },
  "dashboard.satisfactionLabel": { en: "How satisfied are you with the {brand} Prestige Service?", it: "Quanto sei soddisfatto del Servizio Prestige di {brand}?" },
  "dashboard.peaceOfMindLabel": { en: "Does the Prestige Service provide you with peace of mind when using your item?", it: "Il Servizio Prestige ti offre tranquillità quando utilizzi i tuoi articoli?" },
  "dashboard.recommendLabel": { en: "Would you recommend {brand} to others because of this new service?", it: "Consiglieresti {brand} ad altri grazie a questo nuovo servizio?" },
  "dashboard.comment": { en: "Comment", it: "Commento" },
  "dashboard.commentPlaceholder": { en: "Enter comment", it: "Inserisci un commento" },
  "dashboard.submit": { en: "Submit", it: "Invia" },
  "dashboard.continueShopping": { en: "Continue Shopping", it: "Continua lo shopping" },
  "dashboard.continueShoppingDesc": { en: "Continue shopping our finest pieces of jewelry, enjoying peace of mind with our exclusive cover service.", it: "Continua a fare shopping tra i nostri migliori gioielli, godendo della tranquillità del nostro esclusivo servizio di copertura." },
  "dashboard.feedbackSignInError": { en: "Sign in again to send feedback.", it: "Accedi di nuovo per inviare feedback." },
  "dashboard.feedbackEmptyError": { en: "Add at least one rating or a comment.", it: "Aggiungi almeno una valutazione o un commento." },
  "dashboard.feedbackSuccess": { en: "Feedback submitted.", it: "Feedback inviato." },

  // Insights
  "insights.title": { en: "AION Program", it: "AION Program" },
  "insights.subtitle": { en: "Live policies only", it: "Solo polizze Live" },
  "insights.covers": { en: "covers", it: "coperture" },
  "insights.uniqueClients": { en: "unique clients", it: "clienti unici" },
  "insights.updatedOn": { en: "Updated on", it: "Aggiornato al" },
  "insights.allBrands": { en: "All Brands", it: "Tutti i brand" },
  "insights.filter.allTime": { en: "All time", it: "Tutto il periodo" },
  "insights.filter.last30": { en: "Last 30 days", it: "Ultimi 30 giorni" },
  "insights.filter.last90": { en: "Last 90 days", it: "Ultimi 90 giorni" },
  "insights.filter.thisYear": { en: "This year", it: "Anno corrente" },
  "insights.filter.last12m": { en: "Last 12 months", it: "Ultimi 12 mesi" },
  "insights.filter.allShops": { en: "All stores", it: "Tutti i negozi" },
  "insights.noData": { en: "No live policies found for this brand.", it: "Nessuna polizza live trovata per questo brand." },
  "insights.noRegData": { en: "No registration data available.", it: "Nessun dato di registrazione disponibile." },
  "insights.tab.overview": { en: "Overview", it: "Overview" },
  "insights.tab.weekly": { en: "Weekly", it: "Settimanale" },
  "insights.tab.monthly": { en: "Monthly", it: "Mensile" },
  "insights.tab.deepDive": { en: "Client deep dive", it: "Deep dive clienti" },
  "insights.tab.regTime": { en: "Registration time", it: "Tempo registrazione" },
  "insights.tab.tourism": { en: "Tourism", it: "Turismo" },
  "insights.tourism.subtitle": {
    en: "Monthly correlation between Italian tourism (ISTAT) and cover activations, by province.",
    it: "Correlazione mensile tra turismo italiano (ISTAT) e attivazione coperture, per provincia.",
  },
  "insights.tourism.metric": { en: "Metric", it: "Metrica" },
  "insights.tourism.metric.arrivals": { en: "Arrivals (arrivi)", it: "Arrivi" },
  "insights.tourism.metric.presences": { en: "Overnight stays (presenze)", it: "Presenze" },
  "insights.tourism.lag": { en: "Lag (months)", it: "Sfasamento (mesi)" },
  "insights.tourism.lag.help": {
    en: "ISTAT publishes provincial tourism with ~12-month lag, so lag=12 pairs today's activations with the most recent published months. Positive = tourism leads activations.",
    it: "ISTAT pubblica il turismo provinciale con ~12 mesi di ritardo: con lag=12 si abbinano le attivazioni recenti agli ultimi mesi pubblicati. Positivo = il turismo precede le attivazioni.",
  },
  "insights.tourism.refresh": { en: "Refresh ISTAT data", it: "Aggiorna dati ISTAT" },
  "insights.tourism.refreshing": { en: "Refreshing…", it: "Aggiornamento…" },
  "insights.tourism.lastUpdate": { en: "Tourism data updated", it: "Dati turismo aggiornati" },
  "insights.tourism.never": { en: "never", it: "mai" },
  "insights.tourism.noData": {
    en: "No tourism data yet. Click 'Refresh ISTAT data' to ingest the last 36 months.",
    it: "Nessun dato turismo. Premi 'Aggiorna dati ISTAT' per scaricare gli ultimi 36 mesi.",
  },
  "insights.tourism.noCorrelations": {
    en: "Not enough overlapping months to compute correlations. Need at least 6 months of policies in an Italian province.",
    it: "Mesi sovrapposti insufficienti per calcolare le correlazioni. Servono almeno 6 mesi di polizze in una provincia italiana.",
  },
  "insights.tourism.topCorrelations": { en: "Top correlations", it: "Correlazioni principali" },
  "insights.tourism.province": { en: "Province", it: "Provincia" },
  "insights.tourism.pearson": { en: "Pearson", it: "Pearson" },
  "insights.tourism.spearman": { en: "Spearman", it: "Spearman" },
  "insights.tourism.n": { en: "N months", it: "N mesi" },
  "insights.tourism.activations": { en: "Activations", it: "Attivazioni" },
  "insights.tourism.tourism": { en: "Tourism", it: "Turismo" },
  "insights.tourism.timeseries": { en: "Monthly time series", it: "Serie mensile" },
  "insights.tourism.narrative": { en: "AI summary", it: "Sintesi AI" },
  "insights.tourism.narrativeError": {
    en: "Unable to generate summary.",
    it: "Impossibile generare la sintesi.",
  },
  "insights.tourism.unmatched": { en: "Italian shops not mapped to a province", it: "Negozi italiani non mappati su una provincia" },
  "insights.tourism.unmatchedHint": {
    en: "These cities aren't in the comune list, so their policies are excluded. Extend comune_province to include them.",
    it: "Queste città non sono nella lista dei comuni, quindi le loro polizze sono escluse. Estendi comune_province per includerle.",
  },
  "insights.kpi.liveCovers": { en: "Live Covers", it: "Coperture Live" },
  "insights.kpi.uniqueClients": { en: "Unique clients", it: "Clienti unici" },
  "insights.kpi.totalRRP": { en: "Total RRP", it: "RRP totale" },
  "insights.kpi.sellingPrice": { en: "Selling price", it: "Selling price" },
  "insights.kpi.feedback": { en: "Feedback ★", it: "Feedback ★" },
  "insights.kpi.regRate": { en: "Registration rate", it: "Tasso registrazione" },
  "insights.kpi.reviews": { en: "reviews", it: "recensioni" },
  "insights.kpi.ofTotal": { en: "out of", it: "su" },
  "insights.kpi.registered": { en: "Registered", it: "Registrati" },
  "insights.kpi.profilationStarted": { en: "Profilation started", it: "Profilazione iniziata" },
  "insights.kpi.fullProfile": { en: "Profilation completed", it: "Profilazione completata" },
  "insights.kpi.withFeedback": { en: "With feedback", it: "Con feedback" },
  "insights.kpi.ofReg": { en: "of reg.", it: "dei reg." },
  "insights.kpi.satisfaction": { en: "Satisfaction ★", it: "Satisfaction ★" },
  "insights.kpi.recommendation": { en: "Recommendation ★", it: "Recommendation ★" },
  "insights.kpi.peaceOfMind": { en: "Peace of mind ★", it: "Peace of mind ★" },
  "insights.kpi.avgDays": { en: "Avg days", it: "Media giorni" },
  "insights.kpi.medianDays": { en: "Median days", it: "Mediana giorni" },
  "insights.kpi.min": { en: "Min", it: "Min" },
  "insights.kpi.max": { en: "Max", it: "Max" },
  "insights.chart.volumeByShop": { en: "Volume by store (% of total)", it: "Volume per negozio (% sul totale)" },
  "insights.chart.rrpByShop": { en: "RRP by store (% of total)", it: "RRP per negozio (% sul totale)" },
  "insights.chart.catTotal": { en: "Covers, RRP and Customers by category — total", it: "Coperture, RRP e clienti per categoria — totale" },
  "insights.chart.catByShop": { en: "Covers, RRP and Customers by category —", it: "Coperture, RRP e clienti per categoria —" },
  "insights.chart.priceRangeAll": { en: "Covers, RRP and Customers by price range — all", it: "Coperture, RRP e clienti per fascia prezzo — totale" },
  "insights.chart.priceRangeRoma": { en: "Covers, RRP and Customers by price range — Roma", it: "Coperture, RRP e clienti per fascia prezzo — Roma" },
  "insights.chart.priceRangeVenice": { en: "Covers, RRP and Customers by price range — Venice", it: "Coperture, RRP e clienti per fascia prezzo — Venezia" },
  "insights.chart.newProfilationStartedMonthly": { en: "New clients who started profilation per month (% of new clients)", it: "Nuovi clienti con profilazione iniziata per mese (% sui nuovi clienti del mese)" },
  "insights.chart.newProfilationStartedMonthlyByShopPrefix": { en: "Profilation started per month — ", it: "Profilazione iniziata per mese — " },
  "insights.chart.newProfiledMonthly": { en: "New clients who completed profilation per month (% of new clients)", it: "Nuovi clienti con profilazione completata per mese (% sui nuovi clienti del mese)" },
  "insights.chart.newProfiledMonthlyByShopPrefix": { en: "Profilation completed per month — ", it: "Profilazione completata per mese — " },
  "insights.chart.newFeedbackMonthly": { en: "New feedback clients per month (% of new clients)", it: "Nuovi clienti con feedback per mese (% sui nuovi clienti del mese)" },
  "insights.chart.newFeedbackMonthlyByShopPrefix": { en: "With feedback per month — ", it: "Con feedback per mese — " },
  "insights.chart.weeklyCov": { en: "Weekly covers", it: "Coperture settimanali" },
  "insights.chart.weeklyRRP": { en: "Weekly RRP (€k)", it: "RRP settimanale (€k)" },
  "insights.chart.volByShopWeekly": { en: "Volume by store — weekly", it: "Volume per negozio — settimanale" },
  "insights.chart.rrpByShopWeekly": { en: "RRP by store — weekly (€k)", it: "RRP per negozio — settimanale (€k)" },
  "insights.chart.avgRRPclient": { en: "Avg RRP per client — registered vs not registered (€k)", it: "RRP medio per cliente — registrati vs non registrati (€k)" },
  "insights.chart.clientsWeek": { en: "Clients per week — new vs returning", it: "Clienti per settimana — nuovi vs che tornano" },
  "insights.chart.clientsWeekShop": { en: "Clients per week —", it: "Clienti per settimana —" },
  "insights.chart.regPctWeekly": { en: "New registered clients per week (% of new clients)", it: "Nuovi clienti registrati per settimana (% su nuovi clienti della settimana)" },
  "insights.chart.monthlyCov": { en: "Monthly covers", it: "Coperture mensili" },
  "insights.chart.monthlyRRP": { en: "Monthly RRP (€k)", it: "RRP mensile (€k)" },
  "insights.chart.volByShopMonthly": { en: "Volume by store — monthly", it: "Volume per negozio — mensile" },
  "insights.chart.rrpByShopMonthly": { en: "RRP by store — monthly (€k)", it: "RRP per negozio — mensile (€k)" },
  "insights.chart.avgRRPclientMonthly": { en: "Avg RRP per client — registered vs not registered (€k)", it: "RRP medio per cliente — registrati vs non registrati (€k)" },
  "insights.chart.clientsMonth": { en: "Clients per month — new vs returning", it: "Clienti per mese — nuovi vs che tornano" },
  "insights.chart.clientsMonthShop": { en: "Clients per month —", it: "Clienti per mese —" },
  "insights.chart.regPctMonthly": { en: "New registered clients per month (% of new clients)", it: "Nuovi clienti registrati per mese (% su nuovi clienti del mese)" },
  "insights.chart.regPctWeekShop": { en: "Registered per week — ", it: "Registrati per settimana — " },
  "insights.chart.regPctMonthShop": { en: "Registered per month — ", it: "Registrati per mese — " },
  "insights.chart.regPctMonthShopSuffix": { en: " (%)", it: " (%)" },
  "insights.chart.funnel": { en: "Client engagement funnel", it: "Funnel coinvolgimento clienti" },
  "insights.chart.regByShop": { en: "% registered clients by store", it: "% clienti registrati per negozio" },
  "insights.chart.rrpByType": { en: "Avg RRP per client type (€k)", it: "RRP medio per tipo cliente (€k)" },
  "insights.chart.avgCoversPerClient": { en: "Avg covers per client", it: "Polizze medie per cliente" },
  "insights.chart.rrpByShopDetail": { en: "Avg RRP by store —", it: "RRP medio per negozio —" },
  "insights.chart.ticketBandTotal": { en: "% registered clients by ticket band — total", it: "% clienti registrati per fascia scontrino — totale" },
  "insights.chart.ticketBandShop": { en: "% registered by band —", it: "% registrati per fascia —" },
  "insights.chart.geoDistribution": { en: "Geographic distribution of profiled clients (%)", it: "Distribuzione geografica clienti profilati (%)" },
  "insights.chart.genDistribution": { en: "Generational distribution of profiled clients (%)", it: "Distribuzione generazionale clienti profilati (%)" },
  "insights.chart.avgDaysByMonth": { en: "Avg days by activation month", it: "Giorni medi per mese di attivazione" },
  "insights.chart.avgDaysByWeek": { en: "Avg days by activation week", it: "Giorni medi per settimana di attivazione" },
  "insights.chart.regDaysDist": { en: "Registration days distribution", it: "Distribuzione giorni alla registrazione" },
  "insights.label.new": { en: "New", it: "Nuovi" },
  "insights.label.returning": { en: "Returning", it: "Che tornano" },
  "insights.label.registered": { en: "Registered", it: "Registrati" },
  "insights.label.notRegistered": { en: "Not registered", it: "Non registrati" },
  "insights.label.nonReg": { en: "Not reg.", it: "Non reg." },
  "insights.label.covers": { en: "Covers", it: "Coperture" },
  "insights.label.volume": { en: "Volume", it: "Volume" },
  "insights.label.customers": { en: "Customers", it: "Clienti" },
  "insights.label.days": { en: "Days", it: "Giorni" },
  "insights.label.clients": { en: "Clients", it: "Clienti" },
  "insights.label.covers2": { en: "Covers", it: "Polizze" },
  "insights.label.pctRegistered": { en: "% registered", it: "% registrati" },
  "insights.label.uncategorized": { en: "Uncategorized", it: "Non categorizzato" },
  "insights.label.storeNum": { en: "Store", it: "Negozio" },
  "insights.label.newVsReturn": { en: "new vs returning", it: "nuovi vs che tornano" },
  "insights.geo.europe": { en: "Europe", it: "Europa" },
  "insights.geo.americas": { en: "Americas", it: "America" },
  "insights.geo.asia": { en: "Asia", it: "Asia" },
  "insights.geo.mideast": { en: "Middle East", it: "Medio Oriente" },
  "insights.geo.unknown": { en: "Unknown", it: "Sconosciuto" },
  "insights.gen.genZ": { en: "Gen Z", it: "Gen Z" },
  "insights.gen.millennials": { en: "Millennials", it: "Millennials" },
  "insights.gen.genX": { en: "Gen X", it: "Gen X" },
  "insights.gen.boomers": { en: "Baby Boomers", it: "Baby Boomers" },
  "insights.gen.silent": { en: "Silent Generation", it: "Silent Generation" },
  "insights.gen.unknown": { en: "Unknown", it: "Sconosciuto" },

  // Landing (brand selector)
  "landing.intro": {
    en: "To activate AION service, purchase a new product from one of our partner brands and register on the platform.",
    it: "Per attivare il servizio AION, acquista un nuovo prodotto da uno dei nostri brand partner e registrati sulla piattaforma.",
  },
  "landing.selectBrand": { en: "Select your brand below to get started.", it: "Seleziona il tuo brand qui sotto per iniziare." },
  "landing.noBrands": { en: "No brands available.", it: "Nessun brand disponibile." },
  "landing.poweredBy": { en: "Powered by AION Cover", it: "Powered by AION Cover" },
  "landing.back": { en: "Back", it: "Indietro" },
  "landing.comingSoon": { en: "Coming soon", it: "Prossimamente" },

  // Support
  "support.title": { en: "Contact Support", it: "Contatta il Supporto" },
  "support.desc": { en: "Describe your issue and our team will get back to you within 24 hours.", it: "Descrivi il tuo problema e il nostro team ti risponderà entro 24 ore." },
  "support.subject": { en: "Subject", it: "Oggetto" },
  "support.subjectPlaceholder": { en: "Brief summary of your issue", it: "Breve riepilogo del problema" },
  "support.message": { en: "Message", it: "Messaggio" },
  "support.messagePlaceholder": { en: "Describe your issue in detail...", it: "Descrivi il tuo problema in dettaglio..." },
  "support.send": { en: "Send Message", it: "Invia Messaggio" },

  // Admin — Ask the data (AI query chat)
  "aiQuery.title": { en: "Ask the data", it: "Interroga i dati" },
  "aiQuery.subtitle": { en: "Ask AION. Read-only.", it: "Fai domande ad AION. Sola lettura." },
  "aiQuery.newChat": { en: "New chat", it: "Nuova chat" },
  "aiQuery.noChats": { en: "No chats yet", it: "Nessuna chat" },
  "aiQuery.placeholder": { en: "Ask anything about the data…", it: "Chiedi qualsiasi cosa sui dati…" },
  "aiQuery.disclaimer": { en: "Results are capped at 1000 rows. The assistant can occasionally get SQL wrong — verify before acting.", it: "I risultati sono limitati a 1000 righe. L'assistente può sbagliare la query — verifica prima di agire." },
  "aiQuery.empty.title": { en: "Ask anything", it: "Chiedi qualsiasi cosa" },
  "aiQuery.empty.subtitle": { en: "The assistant understands and answers with a summary, table and chart.", it: "L'assistente capisce e risponde con un riepilogo, una tabella e un grafico." },
  "aiQuery.loadingChat": { en: "Loading chat…", it: "Caricamento chat…" },
  "aiQuery.thinking": { en: "Getting started…", it: "Sto iniziando…" },
  "aiQuery.row": { en: "row", it: "riga" },
  "aiQuery.rows": { en: "rows", it: "righe" },
  "aiQuery.showAll": { en: "Show all", it: "Mostra tutte" },
  "aiQuery.showFirst": { en: "Show first 25", it: "Mostra prime 25" },
  "aiQuery.sqlUsed": { en: "SQL used", it: "SQL utilizzata" },
  "aiQuery.download": { en: "Download", it: "Scarica" },
  "aiQuery.downloadCsv": { en: "Download as CSV", it: "Scarica come CSV" },
  "aiQuery.downloadXlsx": { en: "Download as Excel", it: "Scarica come Excel" },
  "aiQuery.downloadFailed": { en: "Download failed", it: "Download fallito" },
  "aiQuery.sendAria": { en: "Send", it: "Invia" },
  "aiQuery.deleteChatAria": { en: "Delete chat", it: "Elimina chat" },
  "aiQuery.error.prefix": { en: "I couldn't answer that — ", it: "Non sono riuscito a rispondere — " },
  "aiQuery.error.couldntSave": { en: "Couldn't save chat", it: "Impossibile salvare la chat" },
  "aiQuery.error.couldntLoad": { en: "Couldn't load chat", it: "Impossibile caricare la chat" },
  "aiQuery.error.couldntDelete": { en: "Couldn't delete chat", it: "Impossibile eliminare la chat" },
  "aiQuery.error.notSignedIn": { en: "Couldn't save chat: not signed in", it: "Impossibile salvare la chat: non autenticato" },
  "aiQuery.error.queryFailed": { en: "Query failed", it: "Query fallita" },
  "aiQuery.error.unknown": { en: "Unknown error", it: "Errore sconosciuto" },
  "aiQuery.suggestion.1": { en: "How many customers signed up in the last 30 days, by brand?", it: "Quanti clienti si sono registrati negli ultimi 30 giorni, per brand?" },
  "aiQuery.suggestion.2": { en: "Top 10 products by number of active covers.", it: "Top 10 prodotti per numero di coperture attive." },
  "aiQuery.suggestion.3": { en: "Open claims grouped by brand and claim type.", it: "Reclami aperti raggruppati per brand e tipo." },
  "aiQuery.suggestion.4": { en: "Monthly new policies for the last 12 months.", it: "Nuove polizze mensili negli ultimi 12 mesi." },
  "aiQuery.suggestion.5": { en: "Average satisfaction rate per brand from feedback.", it: "Soddisfazione media per brand dai feedback." },
  // Brand-scoped variants — a brand user only sees their own brand, so the
  // cross-brand framing ("by brand", "per brand") is dropped.
  "aiQuery.suggestion.brand.1": { en: "How many customers signed up in the last 30 days?", it: "Quanti clienti si sono registrati negli ultimi 30 giorni?" },
  "aiQuery.suggestion.brand.2": { en: "Top 10 products by number of active covers.", it: "Top 10 prodotti per numero di coperture attive." },
  "aiQuery.suggestion.brand.3": { en: "Open claims grouped by claim type.", it: "Reclami aperti raggruppati per tipo." },
  "aiQuery.suggestion.brand.4": { en: "Monthly new policies for the last 12 months.", it: "Nuove polizze mensili negli ultimi 12 mesi." },
  "aiQuery.suggestion.brand.5": { en: "Average satisfaction rate from feedback.", it: "Soddisfazione media dai feedback." },
  "aiQuery.section.suggestions": { en: "Suggestions", it: "Suggerimenti" },
  "aiQuery.section.reports": { en: "Reports", it: "Report" },
  "aiQuery.section.playbooks": { en: "Playbooks", it: "Playbook" },
  "aiQuery.playbook.customer360": {
    en: "Customer 360 brief for: [name, email, phone, or customer id]\n\nBuild the full brief for a store manager about to talk to this customer: identity, full purchase history, lifetime value snapshot, claims and feedback signals, support history, ranked cross-sell recommendations from the customer's brand catalogue, and concrete action items for the call.",
    it: "Brief Customer 360 per: [nome, email, telefono o id cliente]\n\nPrepara il brief completo per uno store manager che sta per parlare con questo cliente: identità, storico acquisti, lifetime value, segnali da reclami e feedback, storico assistenza, raccomandazioni di cross-sell ordinate dal catalogo del brand del cliente e azioni concrete per la chiamata.",
  },
  "aiQuery.playbook.productAnalysis": {
    en: "Product analysis for: [product name, SKU, or catalogue id]\n\nAnalyse the customer base of this product: buyer demographics (city, country, age bands), repeat-purchase rate, top co-owned products (basket affinity), cancellation rate vs brand average, claim profile (rate and dominant types), feedback vs brand average, top shops and seasonality, and recommended actions on bundling, pricing, and targeting.",
    it: "Analisi prodotto per: [nome prodotto, SKU o id catalogo]\n\nAnalizza la base clienti di questo prodotto: demografia degli acquirenti (città, paese, fasce d'età), tasso di riacquisto, top prodotti co-posseduti (affinità di carrello), tasso di cancellazione vs media del brand, profilo reclami (tasso e tipi prevalenti), feedback vs media del brand, top negozi e stagionalità, e raccomandazioni concrete su bundle, prezzo e targeting.",
  },
  "aiQuery.playbook.customer360.title": { en: "Customer 360 brief", it: "Brief Customer 360" },
  "aiQuery.playbook.customer360.searchPlaceholder": { en: "Search by name or email…", it: "Cerca per nome o email…" },
  "aiQuery.playbook.productAnalysis.title": { en: "Product analysis", it: "Analisi prodotto" },
  "aiQuery.playbook.productAnalysis.searchPlaceholder": { en: "Search by name or SKU…", it: "Cerca per nome o SKU…" },
  "aiQuery.playbook.noResults": { en: "No matches", it: "Nessun risultato" },
  "aiQuery.playbook.searching": { en: "Searching…", it: "Ricerca in corso…" },
  "aiQuery.step.lookingUpCustomer": { en: "Looking up the customer", it: "Sto cercando il cliente" },
  "aiQuery.step.pickingSuggestions": { en: "Picking products to suggest", it: "Sto scegliendo prodotti da suggerire" },
  "aiQuery.step.addingSpend": { en: "Adding up what they've spent", it: "Sto calcolando la spesa totale" },
  "aiQuery.step.pullingOrders": { en: "Pulling up their orders", it: "Sto recuperando gli ordini" },
  "aiQuery.step.checkingClaims": { en: "Checking past claims", it: "Sto controllando i sinistri passati" },
  "aiQuery.step.readingFeedback": { en: "Reading their feedback", it: "Sto leggendo i feedback" },
  "aiQuery.step.checkingSupport": { en: "Checking recent support chats", it: "Sto controllando i contatti recenti" },
  "aiQuery.step.findingSimilar": { en: "Finding what similar customers bought", it: "Cerco cosa hanno comprato clienti simili" },
  "aiQuery.step.lookingUpProduct": { en: "Looking up the product", it: "Sto cercando il prodotto" },
  "aiQuery.step.whoBoughtThis": { en: "Looking at who bought this", it: "Sto vedendo chi ha comprato questo" },
  "aiQuery.step.loadingBrand": { en: "Loading brand details", it: "Sto caricando i dettagli del brand" },
  "aiQuery.step.crunching": { en: "Crunching the numbers", it: "Sto elaborando i dati" },
  "aiQuery.step.justMoment": { en: "Just a moment…", it: "Un attimo…" },
  "aiQuery.step.puttingTogether": { en: "Putting it all together…", it: "Sto mettendo insieme tutto…" },
  "aiQuery.playbook.aiBriefButton": { en: "AI brief", it: "Brief AI" },
  "aiQuery.report.monthlyInternal": { en: "Generate the monthly internal report for last month.", it: "Genera il report mensile interno del mese scorso." },
  "aiQuery.report.monthlyInternalPrevious": { en: "Generate the monthly internal report for two months ago.", it: "Genera il report mensile interno di due mesi fa." },
  "aiQuery.report.dailyNewPolicies": { en: "Daily Chubb sales file (new policies) for yesterday.", it: "File Chubb giornaliero (nuove polizze) di ieri." },
  "aiQuery.report.dailyCancelledPolicies": { en: "Daily Chubb sales file (cancellations) for yesterday.", it: "File Chubb giornaliero (cancellazioni) di ieri." },
  "aiQuery.report.dailyClaims": { en: "Daily Chubb claims report for yesterday.", it: "Report Chubb giornaliero dei sinistri di ieri." },

  // Admin home — Chubb upload status widget
  "chubbStatus.title": { en: "Chubb daily files", it: "File giornalieri Chubb" },
  "chubbStatus.lastNDays": { en: "last {n} days", it: "ultimi {n} giorni" },
  "chubbStatus.loading": { en: "Loading recent uploads…", it: "Caricamento upload recenti…" },
  "chubbStatus.empty": { en: "No uploads to show.", it: "Nessun upload da mostrare." },
  "chubbStatus.loadFailed": { en: "Couldn't load upload history", it: "Impossibile caricare la cronologia degli upload" },
  "chubbStatus.loadingFile": { en: "Loading file rows…", it: "Caricamento righe del file…" },
  "chubbStatus.fileError": { en: "Couldn't load file", it: "Impossibile caricare il file" },
  "chubbStatus.noFile": { en: "No file attached to this report.", it: "Nessun file associato a questo report." },
  "chubbStatus.truncated": { en: "Showing first {shown} of {total} rows.", it: "Mostrate prime {shown} di {total} righe." },
  "chubbStatus.colsHidden": { en: "{shown} of {total} columns shown (empty ones hidden)", it: "{shown} di {total} colonne mostrate (vuote nascoste)" },
  "chubbStatus.refresh": { en: "Refresh", it: "Aggiorna" },
  "chubbStatus.attempts": { en: "attempts", it: "tentativi" },
  "chubbStatus.errorLabel": { en: "Error returned by Chubb SFTP", it: "Errore restituito dall'SFTP di Chubb" },
  "chubbStatus.failed": { en: "failed", it: "falliti" },
  "chubbStatus.pending": { en: "pending", it: "in attesa" },
  "chubbStatus.ok": { en: "ok", it: "ok" },
  "chubbStatus.ko": { en: "KO", it: "KO" },
  "chubbStatus.allOk": { en: "All OK", it: "Tutto OK" },
  "chubbStatus.checkingKo": { en: "Checking…", it: "Verifica…" },
  "chubbStatus.directionSent": { en: "Sent", it: "Inviato" },
  "chubbStatus.directionReturned": { en: "Returned", it: "Ricevuto" },
  "chubbStatus.typePolicies": { en: "Policies", it: "Polizze" },
  "chubbStatus.typeClaims": { en: "Claims", it: "Sinistri" },
  "chubbStatus.status.success": { en: "Success", it: "Successo" },
  "chubbStatus.status.failed": { en: "Failed", it: "Fallito" },
  "chubbStatus.status.pending": { en: "Pending", it: "In attesa" },
  "chubbStatus.status.na": { en: "N/A", it: "N/D" },
  "chubbStatus.status.unknown": { en: "Unknown", it: "Sconosciuto" },
  "chubbStatus.alert.title": { en: "Chubb upload issues need attention", it: "Problemi nei caricamenti Chubb da verificare" },
  "chubbStatus.alert.failed": { en: "{n} upload(s) failed in the last 3 days", it: "{n} caricamento/i fallito/i negli ultimi 3 giorni" },
  "chubbStatus.alert.pendingStuck": { en: "{n} upload(s) pending for more than 24 hours", it: "{n} caricamento/i in attesa da oltre 24 ore" },
  "chubbStatus.alert.missingEvents": { en: "{n} cover event(s) from yesterday not uploaded to Chubb", it: "{n} evento/i polizza di ieri non caricato/i su Chubb" },
  "chubbStatus.alert.moreCount": { en: " · +{n} more", it: " · +{n} altri" },
};

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  locale: "en",
  setLocale: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocale] = useState<Locale>(
    () => (localStorage.getItem("locale") as Locale) || "en"
  );

  const handleSetLocale = useCallback((l: Locale) => {
    setLocale(l);
    localStorage.setItem("locale", l);
  }, []);

  const t = useCallback(
    (key: string) => {
      const entry = translations[key];
      if (!entry) return key;
      return entry[locale] || entry.en || key;
    },
    [locale]
  );

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
