// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlmdlskiubfdhywmzgzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbWRsc2tpdWJmZGh5d216Z3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjYzNTUsImV4cCI6MjA4Mzk0MjM1NX0.6b5WhZrxD6Vt1sYxh1PlJSRAVU21MxSeZY64QQ64kJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});